id: A049333E3
title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:16:06.665495
  last_modified_at: 2022-03-01 02:16:06.665502
